### ISSUE TITLE
v1.74.978 Can't pick starting ports and incorrect password errors

### ISSUE THREAD

**Issue by cdwilliams77** [luminati-io/luminati-proxy#77]
No longer able to pick starting ports, password errors when trying to create proxy ports. It is not inserting the password from the zone. Please revert back to last build.

**Comment by thisjustin** [comment]
Seconding this - this is related to what I reported in #76 
Going to also open an issue as a feature request to allow installs of particular versions so that if this happens in the future there is a way to revert back to a working build. As it is there is zero room for error when upgrading and that's a dangerous place to be considering it doesn't seem like there's a large team supporting this (to be clear I don't mean that in a disrespectful way at all - just stating my observation that there seems to be only one or two employees dedicated to supporting the proxy manager).

**Comment by assafza** [comment]
Hi, issue is solved in latest version. thank you for your feedback.
