### ISSUE TITLE
Read and Write to .luminati.json simlink

### ISSUE THREAD

**Issue by koprivajakub** [luminati-io/luminati-proxy#87]
Hello, I have multiple instances running in Docker on mupltiple nodes. I need all of them to share the same configuration. Is possible to read configuration stored in `.luminati.json` and have this file simlinked via `ln -s /shared-folder/.luminat.json /root/.luminati.json`?

**Comment by sk91** [comment]
Hi,

This scenario is not currently supported, we did not run tests or special dev for it.
But, preliminary tests show no problem with running based on symlink config. 

You might face issues when trying to change configuration from ui though since multiple processes will try to write config to the same file.

To update the config you will have to stop all processes, update the config manually (or leave only one process running and update using it's ui) 

And then start them again
