### ISSUE TITLE
Feature request: use socks username to set country/city/.. settings

### ISSUE THREAD

**Issue by jessedepril** [luminati-io/luminati-proxy#9]
We use the socks proxy inside chrome.
It would be a great feature if you can parse the username and use that for the proxysettings.

IE: lum-customer-CCC-zone-gen-country-it would route all traffic through Italy (and ignore the settings inside the GUI).

**Comment by lee-elenbaas** [comment]
If you have access to the code generating the request - you can send proxy-authentication header with the luminati credentials you need
if you do not have access to the code how are you going to change the socks credentials on the fly?
and if you have a code that can change the socks credentials - that same code can also use the luminati proxy rest API and update the proxy definitions to provide whatever settings you from luminati instead of changing the socks credentials

**Comment by jessedepril** [comment]
> if you do not have access to the code how are you going to change the socks credentials on the fly?

We have over 100 chrome instances configured on a machine (different countries & cities).
We would like to use socks proxies with them without having to setup 100+ proxies inside the GUI.
Basically we want the same behaviour as the current HTTP proxy, but with socks.

**Comment by lee-elenbaas** [comment]
if those are chrome instances - why not use the HTTP interface and provide the credentials in?

**Comment by jessedepril** [comment]
Because HTTP proxies are easily detected by the latest cloaking software which doesn't allow us to see the 'real' landingpages we need to verify.

Socks proxies are better in this optic.

**Comment by lee-elenbaas** [comment]
They detect the proxy in the browser settings? or in the request?
if they detect it from the request then our SOCK proxy will be just as detectable since it is simply an interface to our HTTP proxy service

**Comment by MarkusPint** [comment]
Luminati proxy manager seems to ignore the username that I'm configuring in Chrome and gives different proxy users the same IP address.. There's no sessions like there is when using zproxy.luminati.io directly.

Running it like this:
luminati --customer=CUSTOMERNAME --password=PASSWORD --sticky_ip --max_requests=0 --session_duration=14515200

**Comment by lee-elenbaas** [comment]
In version 0.6.4 we added UI and CLI option to allow_proxy_auth that will enable you to send requests with  proxy authentication header

**Comment by marktriston** [comment]
jessedepril, lum-customer-CCC-zone-gen-country-it in this link you can chose the country, is there something similar where you can specify the city as well? I mean to specify country as IT and city ROMA how this link lum-customer-CCC-zone-gen-country-it  should be modified in order to add the city as well?

**Comment by giladno** [comment]
@marktriston you can use the `city` flag: `lum-customer-CCC-zone-gen-country-it-city-rome`

This required a special permission to your account, please contact your success manager for more details.

**Comment by marktriston** [comment]
I appreciate the answer!!! once it is active it should work with lum-customer-CCC-zone-gen-country-it-city-rome correct? thank you so much for your prompt answer!!!

**Comment by giladno** [comment]
That's correct, various flags are available for filtering, such as country/city/state/ASN etc. Your designated success manager can provide you will all the available options.

**Comment by marktriston** [comment]
Appreciate!!! I suppose once you need a state the link should go like lum-customer-CCC-zone-gen-country-us-state-FL-city-miami correct?

**Comment by giladno** [comment]
correct.

**Comment by marktriston** [comment]
I really appreciate your answers!!!
