### ISSUE TITLE
Provide endpoint to reload config

### ISSUE THREAD

**Issue by Lazyshot** [luminati-io/luminati-proxy#99]
As a developer, I want to be able to programmatically trigger a reload of the configuration without having to restart the entire service.

This is in support of a kubernetes deployment method using a secret/configmap to store the configurations. Upon an update of the secret/configmap, I want to be able to force the application to reload this new config.

**Comment by assafza** [comment]
Hello, this is Assaf from Luminati, we are planning to add support for the above. 

In order to develop the urgency of the matter and to be aligned to our customers needs, can you elaborate more on:
- How the current solution is effecting badly on your business?
- What exactly you expect to have as a solution?

Thanks

**Comment by Lazyshot** [comment]
This is not an immediate blocker, but requires a full restart of the application in order for configuration changes to have effect. 

We have a workaround, i.e. manually restarting the pods.

An ideal solution would be a single HTTP endpoint that would reload the configuration file and either restart the service or adjusting to the configuration.

The more typical changes would be limited to the addition/removal of zones and any options within those zones.

**Comment by assafza** [comment]
Hi we have added this to the pipeline of new features. thanks for your feedback.
